### ISSUE TITLE
Air Spain VA

### ISSUE THREAD

**Issue by zaqueo2** [oktal3700/bluebell#1]
Dear Friends,

We admire you for your work and wish you all the best.
We would like you to add our package to BlueBell in the same way that LeipzigAir is included.
I am enclosing the package.
Thank you very much
[BB_Air_Spain_VA.zip](https://github.com/oktal3700/bluebell/files/5151908/BB_Air_Spain_VA.zip)

**Comment by oktal3700** [comment]
done
