### ISSUE TITLE
Simwings support

### ISSUE THREAD

**Issue by rickoo09** [oktal3700/bluebell#10]
Hello there I00

 have two livery I would like to drop in your Bluebell CSL.. What should I upload the file as I try to uplaod as dds but its not allowing me to

**Comment by oktal3700** [comment]
You can upload as png or alternatively use some other file sharing service like Google Drive and post a link to it here.

**Comment by rickoo09** [comment]
Did it approved or I need to send it in png format?

**Comment by oktal3700** [comment]
What you have provided in your other issue is fine. I have closed this issue because we don't need two issues for the same thing.

**Comment by rickoo09** [comment]
Ok, thanks. Just wanted to make sure it was ok thanks again
