### ISSUE TITLE
Simwings support 

### ISSUE THREAD

**Issue by rickoo09** [oktal3700/bluebell#11]
Here is the CSL for the A319 and the B738 that I like to add to your Bluebell
https://drive.google.com/file/d/1XbMjFa3G52HW3_MsqCX4FmAkACyfZclp/view?usp=sharing
https://drive.google.com/file/d/1D-hxieDiEnrWQRlji1sl4Me1O_TutuBu/view?usp=sharing
If there is any issue you can email me at jermainesmith0901984@gmail.com

**Comment by oktal3700** [comment]
done

**Comment by rickoo09** [comment]
Hello good morning I see that the case close did you by any chance get to
add the csl?

**Comment by oktal3700** [comment]
Yes it is added

**Comment by rickoo09** [comment]
Good afternoon I update my bluebell but didn’t see the csl in side.

**Comment by oktal3700** [comment]
It's in `BB_Virtual.zip` via the [download link](https://forums.x-plane.org/index.php?/files/file/37041-bluebell-obj8-csl-packages/)
