### ISSUE TITLE
Alpaca Airways CSL models

### ISSUE THREAD

**Issue by WebMaximus** [oktal3700/bluebell#13]
Hi there, hope you're well!

For some time now, a European airline captain going under the nickname flightdeck2sim has been steaming on YouTube flying online on Vatsim. His community which I'm part of came up with our own kind of VA named Alpaca Airways. With flightdeck2sim's community and Alpaca Airways growing in popularity where often quite an amount of users join in on group flights etc, I figured it would be great to have the Alpaca Airways liveries included in the BB CSL package. For other Vatsim users to see all these aircraft in the correct liveries.

I contacted Bounty2211 who made a separate livery pack for the BB package and had him include the Alpaca Airways CSL models in his package. However, I now realized it would of course have been much better to have the CSL models included in your main BB package. Based on the number of downloads your package has. To reach as many users as possible.

So, if you don't mind adding the Alpaca Airways models to your package, you can download them using the link below:

https://drive.google.com/file/d/1xE_Vgc1QQZsP_OI_c-mfsdK-em0rAdEl/view?usp=sharing

Wishing you a good upcoming weekend and stay safe!

Richard

**Comment by oktal3700** [comment]
Some of these repaints use base models that are not from BB. I don't have copyright permission to use those.

I have added the ones that are actually repaints of BB models.
