### ISSUE TITLE
CSL files

### ISSUE THREAD

**Issue by mrkirry** [oktal3700/bluebell#2]
[CSL.zip](https://github.com/oktal3700/bluebell/files/5152541/CSL.zip)

Good day once again,
Uploading the files that I have made for CSL package 
This includes major Baltic states airlines and aircrafts:

B733 airBaltic "BTI"
B738 airBaltic "BTI"
A320 airBaltic liveries (BTI is the main livery, and 3 special flag liveries - BTIK BTIJ BTIL)
A320 GetJet "GJT"
A330 GetJet "GJT"
B757 airBaltic "BTI"
B757 FlyLAL "LIL"

Thank You very much

**Comment by mrkirry** [comment]
Let me know if You will need script extracts from aircraft.cfg

**Comment by oktal3700** [comment]
done
