### ISSUE TITLE
Help about custom liveries

### ISSUE THREAD

**Issue by danielabadgamero** [oktal3700/bluebell#20]
Hello, I would like to create a new livery for airvalencia virtual airline, but it is not necessary that everybody has it, I just want it for my friends. I tried to create the texture and the .obj file several times, but it doesn't work. I also added a line in the xsb txt file, but nothing. What am I missing?

**Comment by danielabadgamero** [comment]
also, how does model matching work?

**Comment by danielabadgamero** [comment]
i tried to do it but i get this: 
![image](https://user-images.githubusercontent.com/80352980/110527441-406c4380-8117-11eb-85b6-8a91118527ce.png)

**Comment by oktal3700** [comment]
Texture needs to be in PNG or DDS format.

> also, how does model matching work?

Depends which pilot client you use.

**Comment by danielabadgamero** [comment]
in x-pilot? anyway, i dont need the answer because the experts did the work for me (thank you!)
