### ISSUE TITLE
Request to add VLC A319 liveries

### ISSUE THREAD

**Issue by danielabadgamero** [oktal3700/bluebell#21]
Hello, I would like to add the livery for airvalencia, not a vatsim VA but an official IVAO VA. For the moment, we have the livery for the A319. Here is the .jpg file:
ICAO code of aircraft: of course A319
ICAO code of airline: VLC

![A319_VLC](https://user-images.githubusercontent.com/80352980/110828056-f4480d00-8296-11eb-8521-99ce65a3ca61.jpg)

**Comment by oktal3700** [comment]
Done.

**Comment by danielabadgamero** [comment]
Thank you very much!

**Comment by danielabadgamero** [comment]
it doesnt work

**Comment by danielabadgamero** [comment]
do i have to move the files to somewhere else from repaints?

**Comment by oktal3700** [comment]
Everything seems to be correct. You shouldn't have to move them, but I don't know the specifics of xPilot.

**Comment by danielabadgamero** [comment]
so are you sure that if I download squawkbox and use that client it will work? btw, for the liveries to show correctly, do i have to fill the flightplan?

**Comment by oktal3700** [comment]
Honestly it shouldn't matter which client you use. I don't think xPilot really does anything different than XSB. I don't know precisely what you have done and what's not working. As far as I can tell, the files are all fine.

**Comment by danielabadgamero** [comment]
could it be that VLC isnt a vatsim official airline?

**Comment by oktal3700** [comment]
That shouldn't make any difference. Filing a flight plan shouldn't make any difference either.

Vatsim does need to know your 3-letter airline code. XSquawkBox lets you enter this manually; xPilot does not, so I assume it must extract it from your callsign.
