### ISSUE TITLE
Walker Air Transport VA Addition

### ISSUE THREAD

**Issue by Itherflight** [oktal3700/bluebell#22]
Storm Walker, CEO of Walker Air Transport, grants you permission to redistribute the files and liveries for the use of the BlueBell CSL package.

Link to our BB package:
[https://drive.google.com/file/d/19s8l9_rSH6nlPlYNC_ENZp6_sD-JbMa9/](https://drive.google.com/file/d/19s8l9_rSH6nlPlYNC_ENZp6_sD-JbMa9/)

Aircrafts included:

- Airbus A300
- Airbus A300F
- Airbus A300ST
- Airbus A319
- Airbus A320
- Airbus A321
- Airbus A332
- Airbus A333
- Beechcraft Baron 58
- Beechcraft KingAir 200
- Boeing 717-200
- Boeing 727-100
- Boeing 727-200
- Boeing 737-200
- Boeing 737-300
- Boeing 737-700
- Boeing 737-800
- Boeing 737-900
- Boeing 747-400
- Boeing 747-400F
- Boeing 757-200
- Boeing 767-300
- Boeing 777-200ER
- Boeing 777-200LR
- Boeing 777-300ER
- Boeing 787-8
- Bombardier CRJ200
- Bombardier CRJ700
- Bombardier Dash8
- Cessna 172
- Cirrus SF50
- Cirrus SR20
- Embraer E135
- Embraer E145
- Embraer E170
- Embraer E195
- Fokker F50
- Let L410
- McDonnell Douglas MD83
- Saab 340

**Comment by Nekulturny** [comment]
Any chance of this making the next update? Our crews are quite active on Vatsim, would be nice to show our colours ;)

**Comment by oktal3700** [comment]
Done.

I could not add the Beluga, Baron, 727, Cessna, or Cirrus, as these are not repaints of aircraft that are already in the BB package. (And they are very large files so probably not suitable as CSL's anyway, too many polygons).

**Comment by Nekulturny** [comment]
Fantastic, thanks so much!
