### ISSUE TITLE
B748I and F

### ISSUE THREAD

**Issue by JackMenta** [oktal3700/bluebell#25]
Hey there and thank you for the awesome pack.

Would it be possible to add these to the pack?
[Boeing 747-8I](https://forums.x-plane.org/index.php?/files/file/15713-b747-8i-csl/)
[Boeing 747-8F](https://forums.x-plane.org/index.php?/files/file/14189-747-8f-csl/)

Thanks in advance :)

**Comment by oktal3700** [comment]
Hi there. Sorry but I only accept repaints for models that are already in the pack, not any other models that might have been produced by other creators. I don't intend for it to be a megapack containing every CSL that can be found. I never really wanted to be involved with even this level of maintenance, but it just kind of happened by accident and so now I'm stuck with it LOL ;) When I first created the pack I did not expect that it would still be in use so many years later.
