### ISSUE TITLE
Request to upload more Airvalencia aircraft

### ISSUE THREAD

**Issue by danielabadgamero** [oktal3700/bluebell#28]
Good morning. I would like to submit these files for them to appear in the CSL.

![A321_VLC](https://user-images.githubusercontent.com/80352980/119384050-6a6be580-bcc4-11eb-9e9e-b01fa934fe5e.png)
![A332_VLC](https://user-images.githubusercontent.com/80352980/119384054-6b047c00-bcc4-11eb-89b0-c9e54bb6d1eb.png)
![B737_VLC](https://user-images.githubusercontent.com/80352980/119384059-6b9d1280-bcc4-11eb-82ac-8f17e26e3135.png)
![A320_VLC](https://user-images.githubusercontent.com/80352980/119384061-6c35a900-bcc4-11eb-84d3-e99d436f607f.png)

There is an Airbus A321, A330-200 and A320 and a Boeing 737. Here are the ICAO's:

A321: A321
A330-200: A332
A320: A320
B737: B737

**Comment by keckromero** [comment]
+ Airvalencia ICAO is: VLC

**Comment by keckromero** [comment]
A321: A321
A330-200: A332
A320: A320
B737: B737

**Comment by keckromero** [comment]
@oktal3700 Hello! I really don't want to put much pressure, but when do you think the CSLs will be available? Thank you for your nice work!

**Comment by oktal3700** [comment]
Done :)

**Comment by danielabadgamero** [comment]
There's a problem, the texture files aren't there, just the .obj... Could you put the texture files too? I sent them in .png format because github wouldn't let me send them as .dds. Also, I would like you to correct I mistake I made. Sorry, the ICAO of the Boeing 737-800 is B738, I don't know what I was thinking.
Thank you, Daniel.
