### ISSUE TITLE
Airbus A350

### ISSUE THREAD

**Issue by AntonKuf** [oktal3700/bluebell#4]
Good evening! Could you add Aeroflot A359 and others
[BB_Airbus.zip](https://github.com/oktal3700/bluebell/files/5162430/BB_Airbus.zip)

**Comment by AntonKuf** [comment]
Using the selection method, I determined that the VERT_OFFSET  should be 3.5

**Comment by AntonKuf** [comment]
[BB_Airbus.zip](https://github.com/oktal3700/bluebell/files/5177857/BB_Airbus.zip)
I have corrected  VERT_OFFSET

**Comment by oktal3700** [comment]
I don't believe this repaint is a good fit for this package. It is not a repaint of any aircraft that is already in the package. I do not know the origin nor the copyright status of the base model. It might complicate the user experience to have two different packages containing the same model. I suggest you approach the authors of this other package and ask that they include the repaints in their package instead: https://forums.x-plane.org/index.php?/files/file/58902-bluebell-obj8-csl-livery-pack/
