### ISSUE TITLE
RegioAir CSL Packages for Integration

### ISSUE THREAD

**Issue by FreezeManny** [oktal3700/bluebell#48]
> 🔗 Upload or paste a link to the CSL file(s) that you want me to add.
>[(https://drive.google.com/file/d/139IOuWpzEMeYyS_rjRRUiWIPlRl0cHQb/view?usp=sharing)]
> ⚠️ I need you to provide the files, as I do not make them myself. I will only add files that are repaints of models that are already in the package.
>
> 🛑 You grant me a license to redistribute the files, and you affirm that you have the legal right to grant that license under copyright law.
>
> ✈️ Write here the corresponding aircraft and airline ICAO codes.
(ConfigFile is done, ready and tested. You only need to add it :-) )
A306
A319
A320
A321
A333
A343
B738
B744
B752
B763
B773
B788
CRJ7
E170
C172
LJ45

**Comment by oktal3700** [comment]
Thank you, this makes my job so much easier ❤️

I did just have to fix one mistake in the config (A321_AFF should be A321_RGI). And some of the obj files were using a .dds texture instead of .png but I converted all the textures to .dds anyway. No big deal.
