### ISSUE TITLE
airvalencia more CSLs

### ISSUE THREAD

**Issue by keckromero** [oktal3700/bluebell#49]
Hello, good day!

We have some new CSLs for airvalencia Bluebell:

![B733_VLC](https://user-images.githubusercontent.com/80717072/132120620-db4b3f54-2d9c-42b0-9a67-1b3468a913a5.png)
![B738_VLC](https://user-images.githubusercontent.com/80717072/132120631-a8e9cf4d-7da1-4bca-86f7-d1a02e95382d.png)

If there is any chance: could you try that the 738 does not have winglets? it is not too important, but if possible, we would be happy :)

Have a nice day!

**Comment by oktal3700** [comment]
The 738 texture looks too small? 512x512 but it should be 1024x1024.

**Comment by keckromero** [comment]
![B738_VLC](https://user-images.githubusercontent.com/80717072/132135779-8678d0ae-4b0b-4c81-b386-e1c8b5fecd02.png)

Here you have, sorry

**Comment by keckromero** [comment]
When will you have them ready?

Cheers

**Comment by oktal3700** [comment]
Done
