### ISSUE TITLE
Can you please add our VA liveries to the database?

### ISSUE THREAD

**Issue by SonofPicasso** [oktal3700/bluebell#50]
Hi . Love your work and thanks for the effort.
We have a long lived VA Compass Virtual Airlines. I have some liveries for the CSL files. Is it possible to have them included in the next update for the files please? I have included one for the A388 for you.

Best regards
Robert
[A388_YMA.dds.zip](https://github.com/oktal3700/bluebell/files/7388788/A388_YMA.dds.zip)

**Comment by SonofPicasso** [comment]
Excellent thank you. Ill send them through over a period of time as I need to complete them. I wasn’t sure if you would accept them  ☺  Thanks very much for your help.!

 

Robert

 

From: oktal3700 ***@***.***>
Reply to: oktal3700/bluebell ***@***.***>
Date: Friday, 22 October 2021 at 03:53
To: oktal3700/bluebell ***@***.***>
Cc: SonofPicasso ***@***.***>, Author ***@***.***>
Subject: Re: [oktal3700/bluebell] Can you please add our VA liveries to the database? (Issue #50)

 

Yes of course. Send the rest and they will be in the next update.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SonofPicasso** [comment]
Mat good morning.

Question for the texture sizes.

Do they have to be 1024x1024 or will you accept 2048x2048? The higher resolution gives a better look for the AI.

 

Regards

Robert

 

From: Robert Grant ***@***.***>
Date: Thursday, 28 October 2021 at 08:10
To: oktal3700/bluebell ***@***.***>
Subject: Re: [oktal3700/bluebell] Can you please add our VA liveries to the database? (Issue #50)

 

Thanks for the info and your patience. 

 

Robert

 

From: oktal3700 ***@***.***>
Reply to: oktal3700/bluebell ***@***.***>
Date: Thursday, 28 October 2021 at 02:24
To: oktal3700/bluebell ***@***.***>
Cc: SonofPicasso ***@***.***>, Author ***@***.***>
Subject: Re: [oktal3700/bluebell] Can you please add our VA liveries to the database? (Issue #50)

 

Hi Robert

Email attachments won't work. You have to go to the GitHub issue page #50 and attach the files to a comment there.

Mat

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oktal3700** [comment]
They can be any resolution supported by X-Plane, thanks for asking.

**Comment by oktal3700** [comment]
And yes, leave the issue open for the extra aircraft, thanks.

**Comment by SonofPicasso** [comment]
Hello again
Attached the first tranche of our VA aircraft. Ive done it up as BB_Compass_VA with all required files to just drop in the Bluebell parent folder. Hope this is OK.
more to come as I complete them

Robert

[BB_Compass_VA.zip](https://github.com/oktal3700/bluebell/files/7524589/BB_Compass_VA.zip)

**Comment by SonofPicasso** [comment]
did it agin ..ggrrrr silly me

**Comment by SonofPicasso** [comment]
[A306_Cargo.dds.zip](https://github.com/oktal3700/bluebell/files/7544021/A306_Cargo.dds.zip)

Hello again. Could you please replace the dds file in BB_Compass_VA/Airbus/A306/A306_Cargo.dds with the file in the zip file? We have made a couple of adjustments. Thanks again for you great work.

**Comment by SonofPicasso** [comment]
Hi Mat. Another updated dds file for the B738 for BB_Compass_VA please

[B738_Sharkfin.dds.zip](https://github.com/oktal3700/bluebell/files/7566888/B738_Sharkfin.dds.zip)

**Comment by oktal3700** [comment]
All done. Please open a new issue if you have any more updates.
