### ISSUE TITLE
AirVLC New Update CSL

### ISSUE THREAD

**Issue by keckromero** [oktal3700/bluebell#58]
Hey mate, how is everything going?

We tried to improve some of our CSL (738 and A319) for BB_Repaints

ICAO: VLC 

We attach you the two textures in PNG 1024x1024.

This time we would need a bit different model for the 738, we would love it to have winglets!

Hope you can do it without any trouble

Cheers

**Comment by keckromero** [comment]
![B738_VLC](https://user-images.githubusercontent.com/80717072/146419107-9b32d577-e7b5-4f8c-9fda-7dc2fe43e4e2.png)
![A319_VLC](https://user-images.githubusercontent.com/80717072/146419120-f06026ef-2ed9-4ee0-9aff-ce8b74f5dd68.png)

**Comment by keckromero** [comment]
Good day!

Just to know, will it be ready before Tuesday? 

We would really appreciate it

Cheers

**Comment by oktal3700** [comment]
I will try.

**Comment by oktal3700** [comment]
'Tis done.
