### ISSUE TITLE
CSL Files

### ISSUE THREAD

**Issue by mrmcnuggetboi** [oktal3700/bluebell#6]
Im curious does the new CSL files in this repository have gear tilt on touchdown and touchdown smoke? I saw some of those things in the datarefs? (for VATSIM/Xpilot). If not Im wondering if it would be possible to support those things for VATSIM?

**Comment by oktal3700** [comment]
They have many datarefs left over from the WorldTraffic models. The clients (xPilot/XSquawkBox/swift) probably don't know these datarefs, so it would be for the client developers to add support for those if they can.
