### ISSUE TITLE
Folders in ZIP-files

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [oktal3700/bluebell#60]
Hi Mat, could we check all the ZIP-files to make sure they contain suitable folder-names?

For example, the Airbus1 and Airbus2 ZIP-files contain BB_Airbus folders that then hold all the subfolders with aircraft types. That is good, because it will reduce the chance of users extracting and installing them incorrectly. The ZIP-files for Boeing1, Boeing2 and Boeing3 all contain the aircraft types directly. It would be beneficial, I think to pack each of them into BB_Boeing. Other ZIP-files also contain the aircraft-type directories instead of the directory-name that they should be installed into.

This may help to make the installation instructions the same for all files.

**Comment by oktal3700** [comment]
My mistake. Thanks very much for pointing it out, Andreas. Fixed now.
