### ISSUE TITLE
FIX CSL 738

### ISSUE THREAD

**Issue by keckromero** [oktal3700/bluebell#62]
Hello!

We noticed a pink colour in the front of the B738 CSL of the newest VLC CSL.

Is that something we could fix?

The B738 needs winglets

Best regards and Happy new year!

**Comment by keckromero** [comment]
![B738_VLC](https://user-images.githubusercontent.com/80717072/148059701-dca8fb74-0010-4c31-aca7-32f74c69b236.png)

Could you compare both?

The old one and the we think is working?

Thanks again!

**Comment by oktal3700** [comment]
Sure thing. It will have to be next week, very busy at the moment.

**Comment by oktal3700** [comment]
Done

**Comment by keckromero** [comment]
Thanks!!
