### ISSUE TITLE
Missing textures in PNG zip files

### ISSUE THREAD

**Issue by srcejon** [oktal3700/bluebell#63]
Great package - thanks!

It seems there some missing textures from the PNG zip files:

A318/A318_LAN.png
A318/A318_LNE.png

B738/B378_ABB.png and all other aircraft with winglets

B752/B75F_LIT.png should possibly be named B752/B752_LIT.png
B752/B752_ABQ.png  
B752/B752_BZS.png  
B752/B752_FWA.png  
B752/B752_SWI.png  
B752/B752_SWV.png  
B752/B752_XAS.png

B763/B763_ABB.png
B763/B763_ABN.png
B763/B763_ABZ.png
B763/B763_AFF.png
B763/B763_AGA.png
B763/B763_AHS.png
B763/B763_AMZ.png
B763/B763_ARC.png
B763/B763_ARW.png
B763/B763_AZG.png
B763/B763_BHA.png
B763/B763_CNS.png
B763/B763_EBA.png
B763/B763_EMI.png
B763/B763_EMR.png
B763/B763_EUK.png
B763/B763_FUN.png
B763/B763_GAL.png
B763/B763_GRE.png
B763/B763_JGO.png
B763/B763_PRY.png
B763/B763_SUN.png
B763/B763_SWI.png
B763/B763_SYT.png
B763/B763_TBA.png
B763/B763_XAS.png

B788/B788_LIT.png
B788/B788_ETD.png
B788/B788_NAX.png

B74F/B74F_BAW.png
B74F/B74F_CCA.png
B74F/B74F_DHK.png
B74F/B74F_JGO.png

B77L/B77L_PVI.png
B77L/B77L_SUN.png
B77L/B77L_SWI.png
B77L/B772_LIT.png   Although possibly models should be update to refer to B77L_LIT.png 

B77W/B77W_VIR.png
B77L/B773_LIT.png   

B772/B772_LIT.png   

B773/B773_LIT.png   

B744/B744_ABN.png   
B744/B744_ABZ.png   
B744/B744_ARW.png   
B744/B744_BHA.png   
B744/B744_CNS.png   
B744/B744_EMI.png   
B744/B744_EMR.png   
B744/B744_EUK.png   
B744/B744_FLO.png   
B744/B744_FUN.png   
B744/B744_GAL.png   
B744/B744_JGO.png   
B744/B744_MHL.png   
B744/B744_SUN.png   
B744/B744_SWI.png

**Comment by srcejon** [comment]
Also, the BB_Mil PNG zip has nearly all textures missing.

**Comment by birdydma** [comment]
Either you have a very old set of BB (There is only .dds in the actual BB set), either you are speaking of  the X-CSL set (They are in the .png format). Check your install.

Issue can be closed.

**Comment by oktal3700** [comment]
All PNG textures in BB have been converted to DDS for performance reasons. The original PNG files are provided in separate zip files so they are not lost. They could be useful for people making repaints or whatsoever. But they are not useful for regular users. And some DDS files do not have corresponsing PNG files because they were always DDS from the beginning.
