### ISSUE TITLE
DH8D SkyWork Airline (SRK) Livery

### ISSUE THREAD

**Issue by mb-simulations** [oktal3700/bluebell#64]
The Dash 8 SRK livery always shows the old livery which was only used until 2011. The old one is the livery file called "SRK.png" the new livery is already in there called "SRK2.png" Would it be possible to switch those so the first one will be preferred or even completely removed.

**Comment by birdydma** [comment]
SRK.png and SRK2png are X-CSL things. New livery is now in the DB. Topic can be closed.
