### ISSUE TITLE
Skyward Air Liveries

### ISSUE THREAD

**Issue by CaptainGodual** [oktal3700/bluebell#70]
Hello, 

Can you please add the following to the BB for Skyward Air Virtual?

Airbus:
A306
A321

Boeing:
B738

https://1drv.ms/u/s!Aml58Nm4M5NohKAENQFzvCozBqMJ1g?e=wfAJ61

This is what I have so far will have more, more then likely to submit.
![A306-SYW](https://user-images.githubusercontent.com/31859651/164147304-6ba81994-c308-4d93-885d-0c0b7e881ca1.png)
![B738-SYW](https://user-images.githubusercontent.com/31859651/164147316-6261ee75-9a1c-4bd4-82e1-79e428c039ce.png)
![A321-SYW](https://user-images.githubusercontent.com/31859651/164147517-7df38c8e-4984-4314-abe1-2b150e2c3181.png)

**Comment by CaptainGodual** [comment]
Hello, just following up on this as it'd been a few months. I just thought I'd see if it's done yet?

**Comment by oktal3700** [comment]
It is quite an involved process, each time I add some new repaints to the package. You said you would have more, so I wanted to wait to see if those would appear before I add them. But if those won't be ready for some time then I will see if I can add what you have provided so far, this weekend.

**Comment by CaptainGodual** [comment]
I understand, I will be getting more made. So maybe the logical thing would be to wait for me to add more to this submission that way your not doing alot of work.
