### ISSUE TITLE
Serene Air and Airblue

### ISSUE THREAD

**Issue by umarwali34** [oktal3700/bluebell#74]
Hello, 
Could you please add the following liveries to csl package.
1) Serene Air B738
2) Airblue A321/A320

Liveries are available on xplane org. or i can send them to you. Thanks

**Comment by oktal3700** [comment]
Please provide links to the relevant x-plane.org download pages. Are you the creator of the liveries?

**Comment by umarwali34** [comment]
Serene Air
https://forums.x-plane.org/index.php?/files/file/72643-sereneair-boeing-737-800x-zibo/

Airblue A321
https://forums.x-plane.org/index.php?/files/file/75964-airblue-ap-boe-toliss-a321neo/
and
https://forums.x-plane.org/index.php?/files/file/74654-airblue-ap-bmw-toliss-a321ceo/

Airblue A320
https://forums.x-plane.org/index.php?/files/file/46920-air-blue-ff-a320-livery/

I am not the creator of these liveries. I am using these liveries in xplane but these are not shown in vatsim xpilot.

**Comment by oktal3700** [comment]
Those are liveries of flyable aircraft (namely the FlightFactor, Toliss, and Zibo). As such, they can't be used as CSL as it is a different file format.
