### ISSUE TITLE
AirAsia India (ICAO: IAD) A320

### ISSUE THREAD

**Issue by ghosh9691** [oktal3700/bluebell#8]
Please add AirAsia India A320 aircraft. 

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwifu9Swwr7sAhVkYTUKHc9tBbgQmhMwGnoECCEQAg&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FAirAsia_India&usg=AOvVaw1wQy4aYV_aYN3VWUa5zdKk

**Comment by oktal3700** [comment]
I don't make the CSL files, I only package files made by others. So if you actually _have_ a CSL then please let me know about it, otherwise this is not the appropriate venue.
