### ISSUE TITLE
new VA Roma Airways

### ISSUE THREAD

**Issue by captainvin** [oktal3700/bluebell#9]
[CSL.zip](https://github.com/oktal3700/bluebell/files/5539271/CSL.zip)
Hi, I created new CSL for my VA Roma Airways. 
Is it possible to add them to the package?
Thanks

**Comment by oktal3700** [comment]
Hi, it looks like you intended to include an A332, but it's missing from the zip file?

**Comment by captainvin** [comment]
hi, you are right. sorry. 
Check now :)
[CSL.zip](https://github.com/oktal3700/bluebell/files/5685031/CSL.zip)

**Comment by oktal3700** [comment]
done
